global:
  scrape_interval: 15s


scrape_configs:
  - job_name: 'DeokhuGam Server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
  - job_name: "Node Exporter"
    static_configs:
      - targets: ['node-exporter:9100']